### ISSUE TITLE
Upgrade Print Statements in Repository to Logging Or Remove them

### ISSUE THREAD

**Issue by flea1lt** [sentinel-group/sentinel-rust#142]
There are some print statements in this repo which maybe used for debug, simply remove or wrap them use `logging::debug!()`.

- [write_task](https://github.com/sentinel-group/sentinel-rust/blob/950b4fa92b1419e2b9b7198dc46208c2a33d568a/sentinel-core/src/core/log/metric/aggregator.rs#L47)
- [do_aggregate](https://github.com/sentinel-group/sentinel-rust/blob/950b4fa92b1419e2b9b7198dc46208c2a33d568a/sentinel-core/src/core/log/metric/aggregator.rs#L76)
- [rule_json_array_parser](https://github.com/sentinel-group/sentinel-rust/blob/950b4fa92b1419e2b9b7198dc46208c2a33d568a/sentinel-core/src/datasource/property.rs#L14)

**Comment by Forsworns** [comment]
Yes, these `println` should be removed.

As for the logger, in fact, it would be better to remove the realistic instantiation of the logger, since `sentinel` is an SDK. It should only use the abstract interfaces in `log` crate and remove the `env_logger` and `log4rs` impls. Maybe it's another huge topic worth a new issue...
