### ISSUE TITLE
psutil host level is not supported macos

### ISSUE THREAD

**Issue by eliasyaoyc** [sentinel-group/sentinel-rust#2]
at the begining, i want to run cargo test on macos. unfortunately i saw the error about psutil.
so i looked through the documentation and found that it was not supported.

**Comment by eliasyaoyc** [comment]
![image](https://user-images.githubusercontent.com/46013886/132272230-a711f5ae-a446-4270-afb3-01b3bb321730.png)

**Comment by Forsworns** [comment]
I didn't consider the multi-platform portability since it is still at the very beginning of sentinel-rs development. The tests are carried on Ubuntu 18.04 with rustc 1.53.0.

In fact, not only `psutil`, it would be better to remove other dependencies if possible. Currently, it depends on plenty of crates. The PRs are always welcomed if someone is experienced in these jobs.

**Comment by Forsworns** [comment]
The `psutil` is not maintained actively, one of its dependency is deprecated in `crates.io`, the tracing is now migrated to another crate named `sysinfo`. It supports following OSs:

- Android
- iOS
- Linux
- macOS
- Raspberry Pi
- Windows

Personally, I only focus on the tests on Linux now. I'm not sure whether `sysinfo` does work on other OSs or not.

**Comment by sczyh30** [comment]
Does it work well under container env?

**Comment by Forsworns** [comment]
Yep, it works. I forget this... I will add git actions scripts for other OS environments soon :)

**Comment by Forsworns** [comment]
All the unit tests passed on platforms including Ubuntu 20.04, macOS Catalina 10.15 and Windows Server 2019, which are also the default environments in GitHub-hosted runners.
